### ISSUE TITLE
Bars don't render on IE

### ISSUE THREAD

**Issue by kruser** [kruser/pitchfx-site#28]
IE11 doesn't like our progressBar bindings. See the screenshot.

![image](https://f.cloud.github.com/assets/2208700/2119024/5a530aa2-9139-11e3-8ff5-632f951d673c.png)

**Comment by albertlyu** [comment]
Based on the browser console log, it appears that there is an issue with IE10 compatibility with highcharts.js. I've tested in IE10 and IE9 browser mode and am receiving multiple console errors:

```
SCRIPT5007: Unable to get property 'pointerType' of undefined or null reference 
highcharts.js, line 172 character 209
```

**Comment by kruser** [comment]
@albertlyu, for the bars, I'm not using highcharts to render them, they're just simple bootstrap progress bars. I know what the issue is though, it's in the AngularJS binding of the value.

**Comment by kruser** [comment]
fixed and published to pitchfx.org
