### ISSUE TITLE
Coefficients in wOBA calculation needs to be season-dependent

### ISSUE THREAD

**Issue by albertlyu** [kruser/pitchfx-site#32]
In stats.js, a function for calculating wOBA named 'calcwOBA' was written in lines 155-159 using Tom Tango's wOBA formula from The Book.

```
function calcWOBA(results) {
    if (results.plateAppearances) {
        results.wOBA = ((results.walks * 0.72) + (results.hitByPitch * 0.75) + (results.singles * 0.9) + (results.doubles * 1.24) + (results.triples * 1.56) + (results.homeRuns * 1.95) + (results.rboe * 0.92)) / results.plateAppearances;
    }
}
```

However, Tango's formula from The Book were based on standardized linear weights in order to find those wOBA coefficients. Since then, Tango has developed customized wOBA calculations based on seasonal run environments in order to more accurately assign the relative value of events. wOBA coefficients should be seasonal.

For more information, here are some links to read:
http://www.beyondtheboxscore.com/2011/1/4/1912914/custom-woba-and-linear-weights-through-2010-baseball-databank-data
https://spreadsheets.google.com/spreadsheet/pub?key=0AuazhUE5lzIsdFgzdGlpUzktN2h4Q214a1dMTzBjd3c&gid=0

If we can write a script that determines wOBA coefficients after a season has completed (and use the default wOBA coefficients in Tom Tango's The Book during the season), that can feed the calcwOBA formula more accurately. Then we wouldn't have to rely on Matt Klaassen to update his numbers from the links above.

Edit: FanGraphs has the latest wOBA coefficients on their website. http://www.fangraphs.com/guts.aspx

**Comment by kruser** [comment]
Thanks @albertlyu, this is really helpful.

What do you think would be best to do when you're looking at stats that cross multiple years?

Also note, we use wOBA for the Hit Quality Bubble chart. Those values are in the UI code here:
https://github.com/kruser/pitchfx-site/blob/master/app/app/scripts/pojos/Pitch.js#L64-L86

@albertlyu, if you're interested in helping out with code let me know. This one might be a good place to get your feet wet.  I'd be happy to walk you through setting up your database and pulling down the code.

**Comment by albertlyu** [comment]
Hi there @kruser. I am very interested in contributing, and I agree, this is absolutely a great place to get my feet wet. I have some JavaScript experience, a little bit of D3.js and jQuery, but I have not been intimately exposed to Node.js or MongoDB technologies until now.

I just forked atbat-mongodb if you don't mind, and am working through your readme file. I'm installing the Perl modules at the moment -- your instructions are very clear, so I don't foresee any issues with setting up, but I will contact you if I do have any questions. Thanks a lot!

**Comment by kruser** [comment]
Before you write a lot of code for this, let's talk about where we want to store the coefficients. We'll be adding other stats like FIP to the site and we should come up with a general system for these things.

My initial take is that these numbers aren't changing enough to warrant making them part of the database. Putting them in code would be cleaner and more portable. For the backend, a simple class that holds these coefficients and offers a mechanism to get the best one for the time period would be ideal.

something like...

``` javascript
/**
 * @param {Moment} start - starting date
 * @param {Moment} end - ending date
 * @returns {Array} 
 */
function getWObaCoefficients(start, end) {
   /* do stuff here */
}
```

As this need to be shared between backend and UI so I'll start thinking about how we can write this JS file once and have it propagate to the UI scripts as well.

**Comment by albertlyu** [comment]
In that case, the answer to your question on how to calculate season-dependent stats spanning multiple seasons should be straightforward. A function such as getWobaCoefficients() or getFIPConstants() can source from the same annually-updated table that stores coefficients by season (and to your point about infrequent changes to these numbers, these can simply be a text file that's managed by us, cross-checked with http://www.fangraphs.com/guts.aspx). For each season in the date range, the coefficients are retrieved by the function and could return an array of the coefficients with length n = # of years in date range. Then in calcWOBA(), the input 'results' can be partitioned by season, and the wOBA coefficients by season can be applied in a linear combination with the respective season's results.

Park factors and other adjustments can also be managed in a similar manner, but the coefficients for these adjusted stats are at the season-park dimension instead of simply at the season dimension.

**Comment by kruser** [comment]
@albertlyu, agreed. Not a text file though, make it a javascript data structure inside of this new service. I would call it statsConstantsService.js and put it here: https://github.com/kruser/pitchfx-site/tree/master/app/lib/services

**Comment by albertlyu** [comment]
@kruser, would we need to hard-code the coefficients into a JS object within statsConstantsService.js? Or we could somehow do a JavaScript call to http://www.fangraphs.com/guts.aspx ?

**Comment by kruser** [comment]
@albertlyu , Fangraph's doesn't offer any contract or API with that page so we can't use it. Also, I don't think it would be a good idea to slow down the page load times waiting for pitchfx.org to contact fangraphs data.

Just setup the data like so in the js file....

``` javascript
var yearlyCoefficients = {
  '2014' : {
     'w1B' : 0.888,
     'w2B' : 1.271,
     'w3B' : 1.616,
     .......
  },
  '2013' : {
    ....
  },
  '2012' : {
    ....
  },
 .../* all other years */
}
```

NodeJS will efficiently cache that js file in memory so we won't pay a penalty to get the desired year.

**Comment by albertlyu** [comment]
Tango's formula in 'The Book' has RBOE (reached base on error) in his wOBA formula. But it appears that FanGraphs' wOBA calculation may not take RBOE into account - 1) FanGraphs does not report a coefficient for RBOE in its Guts! wOBA constants page, and 2) These FanGraphs articles, while potentially out-of-date, suggest this to be the case.

http://www.fangraphs.com/library/offense/woba/
http://www.fangraphs.com/blogs/a-visual-look-at-woba/

RBOE happens so infrequently that its inclusion or exclusion in the wOBA formula is relatively trivial. For now, we can keep its coefficient as is (0.92).

**Comment by albertlyu** [comment]
Based on @kruser's previous comments, my attempt at solving #32 now is to create statsConstantsService.js in app\lib\services, storing the variable 'yearlyCoefficients.' calcWOBA would then become:

```
function calcWOBA(results) {
    if (results.plateAppearances) {
        results.wOBA = ((results.walks * yearlyCoefficients[results.year].wBB) 
            + (results.hitByPitch * yearlyCoefficients[results.year].wHBP) 
            + (results.singles * yearlyCoefficients[results.year].w1B) 
            + (results.doubles * yearlyCoefficients[results.year].w2B) 
            + (results.triples * yearlyCoefficients[results.year].w3B) 
            + (results.homeRuns * yearlyCoefficients[results.year].wHR) 
            + (results.rboe * 0.92)) / results.plateAppearances;
    }
}
```

I believe this is the right JS code, but I could be wrong as I have not tested yet. We will need to somehow persist 'year' at the PA dimension through the var 'results'. Is this the data model along the lines of what you were thinking, @kruser? If so, any hints on how I can get the year in which the plate appearance occurred from the atbats collection in the MongoDB database without modifying the db structure?

**Comment by kruser** [comment]
calcWOBA() takes results from the entire set, not just from a single year. How do you plan to approach it when the caller asks for cross-year stats? I would just suggest taking the last year.

If that's the case, you can always count on the inbound filter passing in an end date in the filter.

To get the year from that...

``` javascript
var statsYear = moment().year();
if (filter.date && filter.date.end) {
  var statsYear = moment(filter.date.end).year();
}
// pass statsYear into the calc stats function
```

I would also suggest you use a function in your statsService to get the wOba statics rather than rely on external callers to know inner data structures.

So...

``` javascript
function getWObaCoefficients(statsYear) {
   // read the inner object in here
   return yearlyCoefficients[statsYear];
}
```

**Comment by albertlyu** [comment]
@kruser, I'm curious as to why we have to restrict the WOBA calculations to one set of coefficients. Maybe I'm not fully understanding the technical aspects from your previous comment in this thread, but if the caller asks for cross-year stats, can't we pass in an array of statsYears instead of just the last statsYear (or at least, the first statsYear and last statsYear)? Would performance of the stats load really be affected greatly if we partition results by statsYear? Perhaps passing the indexes of results for which statsYear changes?

**Comment by kruser** [comment]
All stats are presented for the time period, not pre-split by year. So I can ask for a players stats from 2010-2014 and it will give me one wOBA number.

The way the stats are aggregated right now, things like wOBA are performed after all hit types are accumulated, not during.

I'm not saying it can't be done, but it is limited right now. It would take a little bit more of a code refactor.

**Comment by albertlyu** [comment]
Makes sense. Perhaps the cost of refactoring the code (for now) outweighs the potential benefits of metric accuracy, given the other projects we can develop for the site :) Thanks for the quick explanation!

**Comment by kruser** [comment]
@albertlyu , agreed about other projects - like #39

**Comment by LeeZee1** [comment]
I set up a column for "wOBA-against" for each starting pitcher using the season-specific coefficients in GUTS! Now I'm wondering if those coefficients can be used on a game-by-game basis such that there will be a "wOBA-against" value for each game of each starting pitcher for each season using the coefficients of a given season for the calculations of wOBA for the games within that season. 

I'm wondering if those wOBA values for those games would even be meaningful, and if not, what is a meaningful way to calculate wOBA on a game-by-name basis for each year in a range of years? I'm thinking that some of the answer to that depends on how those season-specific weights are actually determined. I realize they are "based on the run environment", but specifically in what way?
