### ISSUE TITLE
Use ui-bootstrap datepicker on desktops

### ISSUE THREAD

**Issue by kruser** [kruser/pitchfx-site#34]
We use an HTML5 input type=date for our start and end dates on the atbat filters.

I'm not a fan of Chrome's date picker on input type=date as it tends to scroll like crazy when you least expect it. On top of that, Firefox and IE don't support that HTML5 input type anyways, so we get poor behavior.

We should see if we can use the ui-boostrap datepicker (already in our code base) when we're not on mobile.

http://angular-ui.github.io/bootstrap/#/datepicker

When on mobile (tablets or phones), the native datepickers are more desirable.

**Comment by kruser** [comment]
Developers - the next time you sync code you'll need to run a

```
bower install
```

... this will prompt an installation of the Modernizr library.

**Comment by albertlyu** [comment]
:+1: Ahh I was wondering why my local version of the site was not getting connected to the database -- turns out I needed a bower install to get Modernizr!
