### ISSUE TITLE
Setup travis-ci build

### ISSUE THREAD

**Issue by kruser** [kruser/pitchfx-site#41]
This task is to setup a travis-ci build so we can tell if pull requests pass things like jshint, karma tests, etc., before pulling them in.

**Comment by albertlyu** [comment]
Out of curiosity, is this related to your changes in kruser/pitchfx-site@52f7d629d4107fe128afde8f5c05376ba02ee2b9, creating somewhat of an automated formatter for the js code? Also I figured I can pick up these best practices along the way, so that my future contributions can have cleaner code.

**Comment by kruser** [comment]
@albertlyu, yes, it will allow for contributions to be pretested. I already have jshint and karma tests setup, but they're not passing... even with my own code ;). You can see for yourself by executing 'grunt jshint' or 'grunt test' from your app folder.

Travis-ci will run these things on checkin. It will be pretty slick.

**Comment by albertlyu** [comment]
Similar to this? If so, very cool.

```
Add more commits by pushing to the master branch on albertlyu/linguist.
 Waiting to hear about a2690b7 — The Travis CI build is in progress · Details
```

https://github.com/github/linguist/pull/972
https://travis-ci.org/github/linguist/builds/19675897

**Comment by kruser** [comment]
Yeah, that's the system. They'll run our unit tests, jshint, etc. Perks of being open-source.

**Comment by kruser** [comment]
As part of this I have refactored all of the javascript so it passes our jshint and is compatible with angular-fullstack yeoman generators.

More to come in a developer guide.

**Comment by albertlyu** [comment]
Sounds good, looking forward to the developer guide!

**Comment by kruser** [comment]
The travis-ci builds are now functional. Details here
https://travis-ci.org/kruser/pitchfx-site

The status is also reported on the Readme.md page at the root of this repository.

The build is running Karma unit tests as well as jshint (linter).

Leaving this open while I write a few Karma tests for existing code. Right now I only have a single test that is testing expect(true).toBe(true) <-- not the best test ;)

**Comment by kruser** [comment]
checked in a few tests tonight. More to come, but enough to close this issue.
