### ISSUE TITLE
Create a developer guide

### ISSUE THREAD

**Issue by kruser** [kruser/pitchfx-site#42]
This task is to write a developer guide markdown page. The readme.md is a little out of date and while it explains how to setup, it doesn't explain our use of...
- AngularJS
- yeoman angular-fullstack generators
- jshint
- karma tests

**Comment by kruser** [comment]
Initial gude here: https://github.com/kruser/pitchfx-site/blob/master/DEVELOPER_GUIDE.md

**Comment by albertlyu** [comment]
For what it's worth, I did not recall (off the top of my head) any problems on Windows following your instructions to install MongoDB, run ETL to fetch data, or Node.js. It could be beneficial for me to reproduce those steps for more detailed and potentially Windows-specific instructions. I thought I had already installed the AngularJS framework, but I don't recall going through your Yeoman generator instructions that you added to the developer guide.

**Comment by albertlyu** [comment]
Although, I just remembered I may have forked/used https://github.com/linnovate/mean in order to get the web app up and running...

**Comment by kruser** [comment]
Hmmmm, not sure what you needed mean for. 

As for yeoman and angular-fullstack, you don't need to install those to run the app. They're just for generating new code files. The generator will build out a test file yo match each source file. Pretty slick stuff.

**Comment by albertlyu** [comment]
Let's forget what I said about the MEAN stack. From now on, I'll try to be more detailed and consistent about my installation process, and inform you just in case there are any issues. 

Anyway, I merged all of your updates, and I tried running grunt serve, but wasn't able to load the site locally. In cmd prompt, I received the following messages:

![image](https://f.cloud.github.com/assets/1390356/2311514/a8868d6a-a2f1-11e3-83d2-53fd362ee167.png)

I then npm install 'd grunt-jsbeautifier and js2xmlparser (in that order) and now the site is working locally again!

**Comment by kruser** [comment]
Ah, sorry @albertlyu. I did add a few new dependencies. Things an 'npm install' would have solved for you... had I told you about that :).

I'll think about how to notify all users about when a new dependency is added. I'm glad you worked your way around it though.

**Comment by albertlyu** [comment]
No worries, the error messages were informative and I figured it had to do with missing NodeJS packages. So running 'npm install' is enough to add all the new dependencies. Good to know.
