### ISSUE TITLE
Add hit scatter charts by zone

### ISSUE THREAD

**Issue by kruser** [kruser/pitchfx-site#43]
A couple things for this one...

1) the pitch speeds on the Pitches tab are not useful for a batter, so when we get this new chart, let's replace that chart with this new one, but only on the batter's card

2) for pitchers, let's move the pitch speeds stacked line chart to right below the pitch types. It is the most interesting stuff for a pitcher

3) this new chart will be a 3x3 grid, each cell with a hit scatter chart overlaid on a field. Each cell of the grid represents a portion of the strike zone. The middle cell should represent the very center of the strike zone, while each cell around it would occupy a small portion of the strike zone and all balls around it. This would allow the user to an at-a-glance view of how a batter goes with a pitch, pulls certain pitches, etc., all based around pitch position. See the mockup below

![image](https://f.cloud.github.com/assets/2208700/2300465/48539cf0-a0f1-11e3-98e7-739e40d876fe.png)

**Comment by kruser** [comment]
This enhancement to the atbat-mondodb project is needed before I can implement this.
https://github.com/kruser/atbat-mongodb/issues/7

**Comment by kruser** [comment]
Developers that have created a DB for this project using atbat-mongodb need to run the commands listed in the linked issue above.

**Comment by kruser** [comment]
This is live on the site now. Closing.

**Comment by albertlyu** [comment]
Trying to see if I can post a picture here off my phone, but I'm seeing Mike Trout with a decent BIP rate on sliders and curveballs down in the zone, but the BIP by zone chart doesn't show BIPs down in the zone. Maybe the y-axis is flipped? I'll take a look again when I get back to my laptop. 

Otherwise, this is fantastic.

**Comment by kruser** [comment]
Doh! I hope not. I'm out for several hours but I'll look into it tonight to
confirm and fix. Thanks Albert.

**Comment by albertlyu** [comment]
Here is Mike Trout in 2013-2014 against changeups. I checked breaking balls and offspeed pitches for a couple of other batters and saw similar results:

![image](https://cloud.githubusercontent.com/assets/1390356/2751198/7ea722ce-c8b8-11e3-8047-a905793b99fd.png)
![image](https://cloud.githubusercontent.com/assets/1390356/2751203/9d61649a-c8b8-11e3-93ac-6fd328bd51ce.png)

**Comment by kruser** [comment]
Ok. I obviously reversed them. Awesome that you can use the app to find
this.

**Comment by albertlyu** [comment]
Yup - already having the BIP rate chart allowed me to cross-check with the new hit scatter charts. Also I did all this chart testing on my smartphone - seamless experience. It was just quite inconvenient that I couldn't post screen captures straight to Github issues on mobile :)

**Comment by kruser** [comment]
I flipped those rows around. I did have the 0th and 2nd row flipped. Thanks for catching that one.
