### ISSUE TITLE
Balls in Play Result

### ISSUE THREAD

**Issue by patrickjmcd** [kruser/pitchfx-site#47]
Especially from a pitcher's perspective, it would be great to either be able to filter the Balls in Play chart by result (Out vs. Safe). Going a step further, if the batter was safe, what was the result?

I know this has the potential to make the chart very messy, but maybe the Balls in Play chart could have a link to pop out to a chart with filters?

**Comment by kruser** [comment]
A picker in the title to swap?

![screen shot 2014-03-07 at 4 08 48 pm](https://f.cloud.github.com/assets/2208700/2362936/0e1bd134-a645-11e3-94ce-7001431d2585.png)
![screen shot 2014-03-07 at 4 08 42 pm](https://f.cloud.github.com/assets/2208700/2362938/1088b572-a645-11e3-820b-85f95db72386.png)

**Comment by kruser** [comment]
By the way, those screenshots above are just mockups - not real. I just put them in for discussion.

**Comment by patrickjmcd** [comment]
Yes! That's exactly what I was thinking.

**Comment by kruser** [comment]
I'd be fine with this then. Marking it as an enhancement. If anybody wants to start it let me know.

**Comment by patrickjmcd** [comment]
I'll give it a shot, but I'm still learning the nuts and bolts of how the site is put together. Might take me a bit.

**Comment by albertlyu** [comment]
@kruser, do you think we could start a general thread in https://github.com/kruser/atbat-mongodb/ with the purpose of helping new developers get set up who have specific questions? Or is there a better practice in Github project collaboration?

**Comment by kruser** [comment]
Sounds good @patrickjmcd, my email and twitter are on the homepage if you need to contact me or Albert while you're getting setup.

Note that the stats.js controller only returns an array of x/y coords keyed by trajectory. So there is server work here too.
https://github.com/kruser/pitchfx-site/blob/master/app/lib/controllers/apis/stats.js#L137-L166

Switching views can either hit a new endpoint on the server, or you can just alter the stats function to return a better payload. Just take care not to increase the payload substantially.

**Comment by kruser** [comment]
@albertlyu, yeah, that's probably a good idea. Let me know where the doc isn't sufficient either. Installing Perl modules can sometimes be a bear.

**Comment by patrickjmcd** [comment]
Sorry that I've been absent for so long on this. I have the site up and running locally and I've been working to break it down to figure out how to make this happen (I'm still very new to AngularJS). I'll keep you all posted on my progress.

**Comment by albertlyu** [comment]
@patrickjmcd, good to hear from ya! I'm still very new to AngularJS as well. I've found ng-newsletter.com to be very useful as well as the many tutorials out there. I also had the benefit of attending an AngularJS workshop here in Chicago. But once you get the gist of the MVC framework, I think a great way to learn is to find an issue to contribute to here, then pick @kruser's brain. That's worked well for me thus far.

**Comment by albertlyu** [comment]
Also great that you were able to get the site up and running! Seems like the documentation works well, even for Windows users, as I was able to follow it beforehand too. Let's keep in mind of future developers who may need help setting up.

**Comment by patrickjmcd** [comment]
Worked just fine for me and I'm on a Mac. 

Documentation was a huge help. 
—
