### ISSUE TITLE
New Domain/Site Name

### ISSUE THREAD

**Issue by kruser** [kruser/pitchfx-site#53]
See #50 for details of the MLBAM cease & desist letter.

This task is to pick a new domain name for the site and update the site header to match.

Anybody out there want to make a logo once we have a name? I'm not a designer.

**Comment by kruser** [comment]
Some possibilities here...

baseballmod.com

**Comment by kruser** [comment]
I really like BaseballMod.com. If I don't hear anything better by tomorrow I'll use that.

**Comment by albertlyu** [comment]
Go for it!
