### ISSUE TITLE
Create a Logo for BaseballMod.com

### ISSUE THREAD

**Issue by kruser** [kruser/pitchfx-site#58]
This issue to create two artifacts for BaseballMod.com.
1. The logo that we can use in the header of the site.
2. The brand logo that we can use as a  favicon and Twitter logo.

SVG preferred for both.

The designer of the used logo will receive attribution on the site attribution page here
https://github.com/kruser/pitchfx-site/blob/master/ATTRIBUTION.md

**Comment by kruser** [comment]
I'm hoping to open up a work item on crowdSPRING for this soon. Until then, I'll take submissions through this GitHub issue.

**Comment by etai07** [comment]
Hi,
Albert told me about this need for the website and I agreed to help out when I had the time. Here's a rough first draft for a logo:
![image](https://cloud.githubusercontent.com/assets/7396771/2791396/5c6a2a38-cbc6-11e3-9cf5-0d769538eee8.png)

**Comment by kruser** [comment]
Awesome. Looking good. That looks like something we could use on our twitter profile.

Any ideas for what could go on the site header and what could go on the favicon?

As far as artifacts go I think we'll need a transparent background svg for the header and a tiny PNG for the favicon.

**Comment by etai07** [comment]
Hi, for the site header you could possibly have a blurred out background of a baseball field/stadium (or something baseball-related) and overlay the logo on top in white text; plus any additional drawings (maybe graphs or numbers). 
I'm imagining something fairly simple and clean like this: http://heathlife.co.uk/
What are your thoughts on how the site header should look?

Eric

**Comment by kruser** [comment]
For the homepage we already have the stadium images. We could put the logo
on top of that. I was assuming we'd put it in the navbar like this, but I
like making it more prominent on the home page like you suggest.

Still though, for player pages we'd need something that fits in the navbar,
kind of like that site does on pages like this.
http://heathlife.co.uk/workshops

**Comment by jodiewychan** [comment]
Hi!

Albert told me about this website as well--and maybe if you're interested here's an icon that I put together, maybe if you'd like you can integrate @etai07 text into it? Just an idea (: 

![screen shot 2014-04-24 at 11 41 37 pm](https://cloud.githubusercontent.com/assets/7191299/2797396/88fe370a-cc2b-11e3-9ae0-05048e2f2fbb.png)

the concept behind the base design was the swing rate visual representation found for baseball players (this particular was a snippet of joe mauer's modified).

**Comment by kruser** [comment]
Thanks Jodi. These are really great and I appreciate the work.

I think I'd lean towards the simplicity of @etai07's design for the main logo. I really like Jodi's baseball/heatmap for a 404 page though so please leave it here for that.

As we use these we'll add notes on our attribution.md page.

@etai07, Could we get some artifacts posted for your image?
- 16x16 png with just the B for the favicon
- lengthwise brand/logo that I can use on the navbar - this is probably an SVG of just the baseballmod text with a transparent background
- SVG of your sample above that I can use on Twitter.

Thanks much.

![image](https://cloud.githubusercontent.com/assets/2208700/2805313/8966ddce-ccb6-11e3-8e18-006c769ca1ef.png)

**Comment by etai07** [comment]
I made a 16x16 and 32x32 png; as well as the logo above converted to .svg format. 
How large should the image be for the navbar? I was thinking of putting the "B" symbol and "baseballmod" all on the same line so they read straight across.

svg file:https://drive.google.com/file/d/0B-dzoLqFJY1KWUM1RnBhSkEtZDg/edit?usp=sharing

![bbm_favicon_16_16](https://cloud.githubusercontent.com/assets/7396771/2811199/0e1714be-ce0e-11e3-8720-98b34a1be4d0.png)

![bbm_favicon_32_32](https://cloud.githubusercontent.com/assets/7396771/2811202/10ce7846-ce0e-11e3-93ac-4767a5551729.png)

**Comment by albertlyu** [comment]
Thanks @etai07 and @jodiewychan! The navbar should handle about 45px height. @etai07, were you thinking of adding the 'B' symbol next to BaseballMod.com? Or maybe using your 'B' design for the whole phrase 'BaseballMod.com'?

**Comment by kruser** [comment]
I think the logo next to the baseballmod name would look redundant. Since
the logo encapsulates the b and m I think it should be left out of the
header.

Feel free to present both options though.

L

**Comment by etai07** [comment]
So I tried out the logo+ text and I agree it looks redundant so I just attached the text for the navbar. Let me know if there's anything that needs to be changed.
https://drive.google.com/file/d/0B-dzoLqFJY1KNF91TGozODV5VE0/edit?usp=sharing

**Comment by kruser** [comment]
Forgive me for being picky :). A couple of questions though..
1. For the favicon.ico at the 16x16 size I can't tell that I'm looking at a letter. Something about the red on blue contrast and the thin letter pixel. Any ideas?
2. For the header logo:
   - it's offset left in the SVG
   - colors? I liked the white for 'baseball' and red for 'mod'. Maybe that text is too thin too though?

**Comment by etai07** [comment]
It's okay, I'm prepared to make modifications as needed.
So I made the "white line" of the "B" thicker to make it stand out more: not sure if this makes it better. 
![bbm_favicon_16_16_v2](https://cloud.githubusercontent.com/assets/7396771/2849163/adcdd070-d0ce-11e3-8e2d-98673a72e718.png)

But if not I could try making the background darker to bring out the contrast; although I'm not sure if that would match with the color scheme of your current website.

For the header logo, I wasn't sure about the colors so I just left them black. Here's the updated site header with the right colors (hopefully). What do you mean by the logo is offset in the left?
https://drive.google.com/file/d/0B-dzoLqFJY1KOUJvVHpreVBXVkE/edit?usp=sharing

**Comment by kruser** [comment]
Regarding the offset, it seems like you're exporting more than just the svg. Notice in Inkscape below, the document is wider than the graphic.

![image](https://cloud.githubusercontent.com/assets/2208700/2849486/3d6cb032-d0db-11e3-917d-bcd616f88909.png)

I'm thinking we should drop the .com too. I liked your original `baseballmod` standalone.

**Comment by etai07** [comment]
Hi, so I changed the colors to match the logo, and edited the canvas size:
https://drive.google.com/file/d/0B-dzoLqFJY1KaGpUNlpfOFJMNzA/edit?usp=sharing

**Comment by kruser** [comment]
Thanks @etai07. Looks good right?

![image](https://cloud.githubusercontent.com/assets/2208700/2873431/d8994252-d3a9-11e3-938c-bd0294e1fd74.png)

I'll push this out to the site sometime today. How do you want to be mentioned on the attribution page? With you twitter logo, email, github page, linkedIn? Let me know.

**Comment by kruser** [comment]
The favicon isn't readable enough yet though.

Check out some of these favicons
http://bootswatch.com/favicon.ico
http://baseballmod.com/favicon.ico
https://www.facebook.com/favicon.ico

**Comment by albertlyu** [comment]
The new navbar looks great, @etai07!

**Comment by etai07** [comment]
thanks @albertlyu 
for site attribution...just state whatever I helped make/design?
also for the favicon, I tried some new designs, what do you guys think?

![bbm_favicon_16_16_draft2_a](https://cloud.githubusercontent.com/assets/7396771/2880595/2e32e0aa-d478-11e3-9943-c3577fc72ddb.png)
![bbm_favicon_16_16_draft2_b](https://cloud.githubusercontent.com/assets/7396771/2880597/31428dc2-d478-11e3-99d5-d87a86fd6e02.png)
![bbm_favicon_16_16_draft2_c](https://cloud.githubusercontent.com/assets/7396771/2880598/3526856a-d478-11e3-88bc-e597c4b5e4d7.png)

**Comment by kruser** [comment]
Eh, BM isn't great. I try to use BBM when I can to avoid the "bowel movement" abbreviation :).

I like your original design. But maybe the line weight and the colors were making it unreadable. If it were all white on blue would it be cleaner?

**Comment by kruser** [comment]
@etai07 , I just pushed my favorite favicon.ico out to the live site so you can get a look at it. I think maybe it is good enough, but feel free to polish it up if you want to make anything about it cleaner.

http://baseballmod.com

**Comment by etai07** [comment]
Hi, the site looks really good and the favicon looks decent.
I think the all white looks alot cleaner so I have it here as well as another copy with red outline with white. 
![bbm_favicon_16_16_draft3_b](https://cloud.githubusercontent.com/assets/7396771/2881961/fff1f846-d488-11e3-8ffd-9bb4996f4bd0.png)
![bbm_favicon_16_16_draft3_a](https://cloud.githubusercontent.com/assets/7396771/2881964/0c4f9706-d489-11e3-8b65-0e8ca4b05dab.png)

Let me know if there's anything else you need: it was a pleasure to work with you.
