### ISSUE TITLE
Whiff % is showing 0% for all pitches

### ISSUE THREAD

**Issue by kruser** [kruser/pitchfx-site#59]
Ughh

![image](https://cloud.githubusercontent.com/assets/2208700/2625971/b22020ac-bdb3-11e3-9b07-5c320c41b500.png)

**Comment by albertlyu** [comment]
Looks like pitchStats.js was missing:

```
if (pitch.isWhiff())
{
    aggregator.whiff++;
}
```

I'm not sure why. I'll investigate. I'm guessing I didn't have an updated local repo when I submitted my pull request.

**Comment by albertlyu** [comment]
See commit 5e0f4975f792de1cd0bcde4ce7ca54a0a6272b7e for the last time whiffs were being aggregated. https://github.com/kruser/pitchfx-site/blob/5e0f4975f792de1cd0bcde4ce7ca54a0a6272b7e/app/app/scripts/controllers/pitchStats.js#L428-L440

When ec6210526c3a068c4fc8d1f09ead1f9859b369b8 was pushed to master, the whiff stats were wiped out. I believe the intention was to remove the `whiffSeries` object, but in doing so, `aggregator.whiff++;` was also removed. https://github.com/kruser/pitchfx-site/compare/5e0f4975f792de1cd0bcde4ce7ca54a0a6272b7e...ec6210526c3a068c4fc8d1f09ead1f9859b369b8#diff-112bb635c769a65c5ead2fd78f47975aR210

I believe the fix would be to add the following to L330-L333 at https://github.com/kruser/pitchfx-site/blob/master/app/app/scripts/controllers/pitchStats.js#L330-L333:

```
if (pitch.isSwing()) {
    aggregator.swing++;
    if (pitch.isWhiff()) {
        aggregator.whiff++;
    }
}
```

I will submit a pull request with these changes later today, for @kruser's review.

**Comment by kruser** [comment]
deploying to site now. I only see you on the site @albertlyu so it's safe to deploy.

FYI, if you don't want to show up on my Google Analytics you can always opt-out on Chrome. That's what I do.
https://tools.google.com/dlpage/gaoptout
