### ISSUE TITLE
Heatmap for Called Strikes?

### ISSUE THREAD

**Issue by kruser** [kruser/pitchfx-site#61]
I like the whiff heatmap but I find I also want to see where batters are getting called strikes. I think a heatmap for this would be fairly simple to put together.

**Comment by albertlyu** [comment]
I like it, but along with this addition of Called Strike Rate, I'd like to propose a higher-level filter for zoneCharts. For example, similar to some of the comments I posed in #39, I'd like to separate out the zoneCharts into separate bags of charts, such as 'Plate Discipline,' 'Batted Ball Results,' and perhaps 'Sabermetric Outcomes.'

As you see in the image below, it's getting crowded on the stacked nav: 

![image](https://cloud.githubusercontent.com/assets/1390356/2672450/1de234c0-c0e7-11e3-99d7-1d70ef7ff150.png)

**Comment by kruser** [comment]
@albertlyu, true. I will organize them in an accordion and open a different issue for that. That shouldn't hold up this issue though.

**Comment by albertlyu** [comment]
Sounds good, an accordion is a good idea. I can work on this issue for called strike rate.

**Comment by albertlyu** [comment]
Are we going with called strikes per pitch? We can, but similar to my reasoning for whiffs / swing, I would find additional value from called strikes / non-swing.

**Comment by kruser** [comment]
I think it should be per pitch. The goal would be to see if the players have a tendency to not swing in certain zones.

It should have nothing to do with if the pitch was actually called a strike or not.

So maybe this is just a "not swing" chart.

**Comment by albertlyu** [comment]
I'm not sure a 'not swing' chart is necessary if that's the case, as the swing rate chart provides the cold zones for that. I think a called strikes chart can also tell us whether a batter is good at understanding the strike zone or prone not to swing at pitches high in the zone vs. down in the zone, inside or outside, etc. 

But ultimately, the called strikes chart may not be as valuable to me as the swings chart and the whiffs charts. A couple of things we can think about when it comes to plate discipline and pitch outcomes. From what I can see, we want these charts to communicate one or more of the following for each zone:
- Swing tendency
- Contact ability
- Zone awareness
- If contact, ball in play ability
- If ball in play, batted ball outcomes
- Overall offensive value or sabermetric outcomes (wOBA, BABIP, etc.)

If a called strikes chart can communicate to us something about zone awareness and swing tendency (or somehow separate zone awareness from swing tendency), I'm all for it.

**Comment by kruser** [comment]
Ok, I'll agree with you that the inverse of the swing rate chart provides what I'm looking for then.

So I'm not going to champion this issue any longer, but I can see your point about a looking strike rate chart. I'd be fine with that going in.

**Comment by kruser** [comment]
Ah, I kind of like this chart. Called Strikes per pitches. Very cool. Merging.....

**Comment by kruser** [comment]
This is live on the site now. I'll try to get the accordion out today too.
