### ISSUE TITLE
Site down: Tried accessing roster API with invalid team

### ISSUE THREAD

**Issue by albertlyu** [kruser/pitchfx-site#71]
I crashed BaseballMod.com. My sincere apologies. So you can access the roster API with this link: http://baseballmod.com/api/roster?team=TOR. What I tried (and knowing this too, since I tried it locally), was accessing the roster API with an invalid team: http://baseballmod.com/api/roster?team=tor. This appears to have broken the site, causing a breakdown between Node and MongoDB I think.

Here are the errors I see in command line when I duplicated the issue. Needless to say, we'll need some way to prevent this from happening since if users try accessing the API through bbm, they could cause the site to go down instantly.

![image](https://cloud.githubusercontent.com/assets/1390356/2761197/8dcba4b2-c9cd-11e3-9333-2bf72348ac60.png)

**Comment by kruser** [comment]
Doh. Fixing it now.

**Comment by kruser** [comment]
back up

**Comment by kruser** [comment]
I put in error handling on that API too
